<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <RimWorldDir Condition="'$(RimWorldDir)' == ''">C:\Program Files (x86)\Steam\steamapps\common\RimWorld</RimWorldDir>
    <Managed>$(RimWorldDir)\RimWorldWin64_Data\Managed</Managed>
    <OutputType>Library</OutputType><AssemblyName>RimMushrooms.SmokeTests</AssemblyName>
    <TargetFrameworkVersion>v4.7.2</TargetFrameworkVersion><LangVersion>7.3</LangVersion>
    <OutputPath>Assemblies\</OutputPath><DebugType>none</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System"/><Reference Include="System.Core"/><Reference Include="System.Xml"/>
    <Reference Include="Assembly-CSharp"><HintPath>$(Managed)\Assembly-CSharp.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>$(Managed)\UnityEngine.CoreModule.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="netstandard"><HintPath>$(Managed)\netstandard.dll</HintPath><Private>false</Private></Reference>
    <Reference Include="RimMushrooms"><HintPath>..\..\Assemblies\RimMushrooms.dll</HintPath><Private>false</Private></Reference>
  </ItemGroup>
  <ItemGroup><Compile Include="SmokeTests.cs"/><Compile Include="MoodTests.cs"/><Compile Include="LightTests.cs"/><Compile Include="AssortedTests.cs"/><Compile Include="HydroponicsTests.cs"/><Compile Include="PoisonTests.cs"/></ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets"/>
</Project>
